# PyTorch Tensor Basic Usage

- Create Tensor
- Indexing,Joining,Slicing
- Initialization
- Math Operations

## 1. Create Tensor
### 1) random numbers

In [6]:
import torch

# torch.rand(sizes) -> [0,1)
# random numbers in range of [0,1)
x = torch.rand(2,3)
x


tensor([[0.0598, 0.0669, 0.9946],
        [0.3677, 0.1905, 0.8294]])

In [7]:
# torch.randn(sizes) -> Z(0,1)
x = torch.randn(2,3)
x

tensor([[ 0.5628, -1.5796,  0.0362],
        [ 0.7211,  0.5880,  1.2392]])

In [8]:
# torch.randperm(n) -> permutation of 0~n
x = torch.randperm(5)
x

tensor([2, 3, 4, 0, 1])

### 2) zeros, ones, arange

In [9]:
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
# torch.ones(2,3) -> [[0,0,0],[0,0,0]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

### 3) Tensor Data Type

In [12]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x

tensor([[4.4943e-35, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [13]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor([2,3])
x

tensor([2., 3.])

In [14]:
# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Numpy to Tensor, Tensor to Numpy

In [15]:
import numpy as np

# torch.from_numpy(ndarray) -> tensor

x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)

x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# tensor.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

### 5) Tensor on CPU & GPU

In [17]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
x_gpu = x.cuda()
x_gpu

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

In [19]:
x_cpu = x_gpu.cpu()
x_cpu

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 6) Tensor Size

In [20]:
# tensor.size() -> indexing also possible

x = torch.FloatTensor(10,12,3,3)

x.size()[:]

torch.Size([10, 12, 3, 3])

## 2. Indexing, Slicing, Joining
### 1) Indexing

In [21]:
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))

x,out

(tensor([[0.4197, 0.5117, 0.4280],
         [0.1608, 0.6812, 0.9271],
         [0.2434, 0.4988, 0.8126],
         [0.9935, 0.7683, 0.9187]]), tensor([[0.4197, 0.5117, 0.4280],
         [0.9935, 0.7683, 0.9187]]))

In [22]:
# pythonic indexing also works

x[:,0],x[0,:],x[0:2,0:2]

(tensor([0.4197, 0.1608, 0.2434, 0.9935]),
 tensor([0.4197, 0.5117, 0.4280]),
 tensor([[0.4197, 0.5117],
         [0.1608, 0.6812]]))

In [23]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

x, mask, out

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead. (Triggered internally at  /pytorch/aten/src/ATen/native/TensorAdvancedIndexing.cpp:733.)
  """


(tensor([[1.1541, 0.0405, 0.3002],
         [0.2280, 0.0404, 0.3727]]), tensor([[0, 0, 1],
         [0, 1, 0]], dtype=torch.uint8), tensor([0.3002, 0.0404]))

### 2) Joining

In [24]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

x,y,z1,z2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3., -1., -2., -3.],
         [ 4.,  5.,  6., -4., -5., -6.]]))

In [25]:
# torch.stack(sequence,dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0)

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### 3) Slicing

In [26]:
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

z1,x_1,x_2,z1,y_1,y_2,y_3

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[ 1.],
         [ 4.],
         [-1.],
         [-4.]]), tensor([[ 2.],
         [ 5.],
         [-2.],
         [-5.]]), tensor([[ 3.],
         [ 6.],
         [-3.],
         [-6.]]))

In [27]:
# torch.split(tensor,split_size,dim=0) -> split into specific size

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 

z1,x1,x2,y1

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [-1., -2., -3.],
         [-4., -5., -6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[-1., -2., -3.],
         [-4., -5., -6.]]), (tensor([[ 1.,  2.],
          [ 4.,  5.],
          [-1., -2.],
          [-4., -5.]]), tensor([[ 3.],
          [ 6.],
          [-3.],
          [-6.]])))

### 4) squeezing

In [28]:
# torch.squeeze(input,dim=None) -> reduce dim by 1

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(),x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [29]:
# torch.unsqueeze(input,dim=None) -> add dim by 1

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x1.size(),x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

## 3. Initialization

In [30]:
import torch.nn.init as init

x1 = init.uniform(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant(torch.FloatTensor(3,4),3.1415)

x1,x2,x3

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  """


(tensor([[4.0125, 8.8952, 6.7750, 8.5945],
         [2.4596, 5.0762, 4.2346, 3.1616],
         [4.1040, 0.4441, 4.5366, 3.8075]]),
 tensor([[-0.1654, -0.0129,  0.3633, -0.0522],
         [ 0.1091, -0.4718,  0.1822, -0.0213],
         [ 0.1150, -0.3221,  0.3217,  0.1411]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

## 4. Math Operations
### 1) Arithmetic operations

In [31]:
# torch.add()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [32]:
# torch.add() broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

x1,x2,x1+10,x2-10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [33]:
# torch.mul() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

x3

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [34]:
# torch.mul() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [35]:
# torch.div() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) Other Math Operations

In [44]:
# torch.pow(input,exponent)

x1 = torch.FloatTensor(3,4)
torch.pow(x1,2),x1**2

(tensor([[0.0786, 0.0000, 0.0000, 0.0000],
         [   nan, 0.0000,    inf,    inf],
         [   inf,    inf,    inf,    inf]]),
 tensor([[0.0786, 0.0000, 0.0000, 0.0000],
         [   nan, 0.0000,    inf,    inf],
         [   inf,    inf,    inf,    inf]]))

In [38]:
# torch.exp(tensor,out=None) 

x1 = torch.FloatTensor(3,4)
torch.exp(x1)

tensor([[ 0.7555,  1.0000,  1.0000,  2.2255],
        [ 2.7183,  3.3201,  1.0000, 21.3809],
        [ 1.0000, 23.1183,  1.0000, 24.9969]])

In [39]:
# torch.log(input, out=None) -> natural logarithm

x1 = torch.FloatTensor(3,4)
torch.log(x1)

tensor([[     nan,     -inf, -86.6356,     -inf],
        [     nan,     -inf,      inf,      inf],
        [     inf,      inf,      inf,  58.1320]])

### 3) Matrix operations

In [40]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.FloatTensor(3,4)
x2 = torch.FloatTensor(4,5)

torch.mm(x1,x2)

tensor([[ 1.3286e-01,  0.0000e+00, -1.9618e-44, -1.9618e-44, -1.8217e-44],
        [        nan,         nan,         nan,         nan,         nan],
        [-6.5454e+30,  1.3211e-12,  2.1813e-12,  2.2428e-12,  2.4073e-12]])

In [41]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [52]:
# torch.dot(tensor1,tensor2) -> dot product of two tensor
##x1 = torch.FloatTensor(3,4)x2 = torch.FloatTensor(3,4)

x1 = torch.tensor([1,2,3,4])
x2 = torch.tensor([2,3,4,5])
x3 = torch.dot(x1,x2)

print(x1)
print(x2)
print(x3)


tensor([1, 2, 3, 4])
tensor([2, 3, 4, 5])
tensor(40)


In [43]:
# torch.t(matrix) -> transposed matrix

x1 = torch.FloatTensor(3,4)

x1,x1.t()

(tensor([[-7.4729e+00,  0.0000e+00,  1.4396e-38,  0.0000e+00],
         [ 3.2230e-44,  0.0000e+00,         nan,         nan],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]),
 tensor([[-7.4729e+00,  3.2230e-44,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.4396e-38,         nan,  0.0000e+00],
         [ 0.0000e+00,         nan,  0.0000e+00]]))

In [53]:
# torch.transpose(input,dim0,dim1) -> transposed matrix

x1 = torch.FloatTensor(10,3,4)

x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [19]:
# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector

x1 = torch.FloatTensor(4,4)
x1

a = torch.symeig(x1,True)
a

torch.return_types.symeig(eigenvalues=tensor([-4.4122e+29, -3.1383e+20,  0.0000e+00,  5.1187e+31]), eigenvectors=tensor([[ 0.0000e+00, -0.0000e+00,  1.0000e+00,  0.0000e+00],
        [ 6.3075e-02,  9.9799e-01,  0.0000e+00,  5.8561e-03],
        [ 9.9372e-01, -6.3346e-02,  0.0000e+00,  9.2260e-02],
        [-9.2445e-02, -9.9334e-11,  0.0000e+00,  9.9572e-01]]))